server:
  port: 8080
  tomcat:
    max-connections: 200
    threads:
      min-spare: 50
      max: 200

spring:
  security:
    user:
      name: admin
      password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    #data: classpath:sqls/dev-*

  h2:
    console:
      enabled: true

  mail:
    host: localhost
    port: 25
    properties:
      smtp:
        auth: false
        starttls:
          enable: false

  jms:
    pub-sub-domain: true

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric


