version: 2.1

orbs:
  maven: circleci/maven@1.2.0

commands:
  build-service:
    description: "Build A Project and push image to dockerhub"
    parameters:
      service-name:
        type: string
    steps:
      # git pull
      - checkout:
          path: ~/poc-workspace

      - setup_remote_docker

      - run:
          name: Login to Dockerhub
          command: docker login -u $MY_DOCKER_ID -p $MY_DOCKER_PWD

      # Download and cache dependencies
      - restore_cache:
          keys:
            - << parameters.service-name >>-{{ checksum "pom.xml"}}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: << parameters.service-name >>-{{ checksum "pom.xml"}}

#      # package into a jar and build image
#      - run: mvn clean package -Ddocker.image.tag=Build-${CIRCLE_BUILD_NUM}-CI -Ddockerfile.maven.settings.auth=false
#
#      # push docker image to docker hub
#      - run: mvn dockerfile:push -Ddocker.image.tag=Build-${CIRCLE_BUILD_NUM}-CI

      - run:
          name: build and push
          command: |
            mvn clean package
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=geeindocker/gitops_poc:$TAG
            docker push geeindocker/gitops_poc:$TAG

      # store raw content of src code
      - store_artifacts:
          path: target/classes
          destination: << parameters.service-name >>

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u242-jdk
    working_directory: ~/fepoc
    steps:
      - checkout
#      - run:
#          name: Determine which directories have changed
#          command: |
#            git diff --no-commit-id --name-only -r `git log -n 2 --oneline --pretty=format:"%h" | tail -n1` | cut -d/ -f1 | sort -u >  projects
#            printf "Modified directories:\n"
#            cat projects
#            while read project; do
#              if grep -Fxq $project project-dirs; then
#                printf "\nTriggerring build for project: "$project
#                curl -s -u ${CIRCLE_TOKEN}: -d build_parameters[CIRCLE_JOB]=${project} https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
#              fi
#            done < projects
      - build-service:
          service-name: "fepoc"

workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
  build_image:
    jobs:
      - build



