version: 2.1

orbs:
  maven: circleci/maven@1.2.0

commands:
  build-service:
    description: "Build A Project and push image to dockerhub"
    parameters:
      service-name:
        type: string
    steps:
      # git pull
      - checkout:
          path: ~/poc-workspace

      - setup_remote_docker

      - run:
          name: Login to Dockerhub
          command: docker login -u $MY_DOCKER_ID -p $MY_DOCKER_PWD

      # Download and cache dependencies
      - restore_cache:
          keys:
            - << parameters.service-name >>-{{ checksum "pom.xml"}}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: << parameters.service-name >>-{{ checksum "pom.xml"}}

      # package into a jar and build image
      - run: mvn clean package -Ddocker.image.tag=Build-${CIRCLE_BUILD_NUM}-CI -Ddockerfile.maven.settings.auth=false

      # push docker image to docker hub
      - run: mvn dockerfile:push -Ddocker.image.tag=Build-${CIRCLE_BUILD_NUM}-CI

      # store raw content of src code
      - store_artifacts:
          path: target/classes
          destination: << parameters.service-name >>

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
  build_image:
    jobs:
      build:
          docker:
            - image: circleci/openjdk:8u242-jdk
          steps:
              - checkout
              - build-service:
                  service-name: "fepoc"


